# pytorch_lightning==1.9.5
seed_everything: 396818285
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: all_parallel
      save_dir: logs
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: drumblender
      log_model: true
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: train
      config: null
      entity: jordieshier
      reinit: null
      tags: null
      group: ablation
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      settings: null
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: validation/loss
      min_delta: 0.0
      patience: 40
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: null
      log_momentum: false
  - class_path: drumblender.callbacks.LogAudioCallback
    init_args:
      on_train: true
      on_val: true
      on_test: true
      save_audio_sr: 48000
      n_batches: 1
      log_on_epoch_end: false
      max_audio_samples: 8
  - class_path: drumblender.callbacks.CleanWandbCacheCallback
    init_args:
      every_n_epochs: 2
      max_size_in_gb: 2.0
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: null
  auto_select_gpus: null
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: -1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: null
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
ckpt_path: null
model:
  class_path: drumblender.tasks.DrumBlender
  init_args:
    modal_synth:
      class_path: drumblender.synths.ModalSynth
    loss_fn:
      class_path: auraloss.freq.MultiResolutionSTFTLoss
      init_args:
        fft_sizes:
        - 1024
        - 2048
        - 512
        hop_sizes:
        - 120
        - 240
        - 50
        win_lengths:
        - 600
        - 1200
        - 240
        window: hann_window
        w_sc: 1.0
        w_log_mag: 1.0
        w_lin_mag: 0.0
        w_phs: 0.0
        sample_rate: null
        scale: null
        n_bins: null
        scale_invariance: false
        eps: 1.0e-08
        output: loss
        reduction: mean
        device: null
    noise_synth:
      class_path: drumblender.synths.NoiseGenerator
      init_args:
        window_size: 256
    transient_synth:
      class_path: drumblender.synths.TransientTCN
      init_args:
        in_channels: 1
        hidden_channels: 32
        out_channels: 1
        dilation_base: 2
        dilation_blocks: 8
        num_layers: 8
        kernel_size: 13
        film_conditioning: true
        film_embedding_size: 128
        film_batch_norm: true
        transient_conditioning: false
        transient_conditioning_channels: 32
        transient_conditioning_length: 24000
    modal_autoencoder: null
    noise_autoencoder:
      class_path: drumblender.models.soundstream.SoundStreamEncoder
      init_args:
        input_channels: 1
        hidden_channels: 16
        output_channels: 128
        kernel_size: 7
        strides:
        - 2
        - 2
        - 4
        - 8
        causal: false
        film_conditioning: false
        film_embedding_size: 128
        film_batch_norm: false
        transpose_output: true
    transient_autoencoder:
      class_path: drumblender.models.soundstream.SoundStreamAttentionEncoder
      init_args:
        input_channels: 1
        hidden_channels: 16
        output_channels: 128
        kernel_size: 7
        strides:
        - 2
        - 2
        - 4
        - 8
        causal: false
        film_conditioning: false
        film_embedding_size: 128
        film_batch_norm: false
        transpose_output: false
    encoder: null
    transient_parallel: true
    transient_takes_noise: false
    modal_autoencoder_accepts_audio: false
    noise_autoencoder_accepts_audio: true
    transient_autoencoder_accepts_audio: true
    float32_matmul_precision: medium
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: false
lr_scheduler:
  class_path: pytorch_lightning.cli.ReduceLROnPlateau
  init_args:
    monitor: validation/loss
    mode: min
    factor: 0.5
    patience: 20
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0.0
    eps: 1.0e-08
    verbose: false
data:
  class_path: drumblender.data.ModalDataModule
  init_args:
    batch_size: 12
    num_workers: 8
    dataset_class: drumblender.data.AudioWithParametersDataset
    dataset_kwargs:
      seed: 5152845
      parameter_key: feature_file
      split_strategy: sample_pack
      expected_num_modes: 64
    url: https://d5d740b2d880827ae0c8f465bf180715.r2.cloudflarestorage.com
    bucket: drum-dataset
    archive: drumblender-percussion-dataset-v1.tar.gz
    meta_file: percussion_metadata.json
    data_dir: dataset/percussion
    data_dir_unprocessed: dataset-unprocessed/percussion-dataset
    sample_rate: 48000
    num_samples: 96000
    num_modes: 64
    min_length: 10
    threshold: -80.0
    hop_length: 256
    fmin: 20
    n_bins: 240
    bins_per_octave: 24
    diff_threshold: 5.0
    save_modal_audio: false
